name: Build V8  

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        version: ['8.4'] #, '8.3']
        platform: ['x64', 'x86']
        lib: ['shared'] #, 'monolith']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python2
      uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key-source: https://api.nuget.org/v3/index.json
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.3.0
      with:
        toolset: '14.2'
    - name: Build
      run: python build.py --version=${{ matrix.version }} --platform=${{ matrix.platform }} --libs=${{ matrix.lib }}
    #- name: Store packages
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: '8.4-${{ matrix.platform }}-${{ matrix.lib }}'
    #    path: '*.nupkg'
    #  continue-on-error: true
    - name: Publish on Nuget.org
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
